/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "background": "#fff8f6",
          "surface-container": "#ffe9e3",
          "secondary": "#006789",
          "primary-fixed": "#ffae80",
          "surface": "#fff8f6",
          "error-container": "#fa7150",
          "on-background": "#4f271a",
          "on-secondary-fixed": "#00455d",
          "primary-dim": "#893d00",
          "surface-variant": "#ffdbd0",
          "surface-bright": "#fff8f6",
          "on-error": "#fff7f6",
          "error-dim": "#821a01",
          "inverse-surface": "#1c0904",
          "on-tertiary-fixed-variant": "#406c00",
          "surface-container-high": "#ffe2da",
          "outline-variant": "#e1a491",
          "outline": "#a36e5d",
          "surface-container-highest": "#ffdbd0",
          "error": "#aa371c",
          "tertiary-container": "#c1fd7c",
          "tertiary-fixed-dim": "#b3ee6f",
          "on-secondary-container": "#005876",
          "secondary-fixed-dim": "#9fddff",
          "on-secondary-fixed-variant": "#006384",
          "on-primary-container": "#662c00",
          "on-tertiary-fixed": "#2c4d00",
          "surface-dim": "#ffd0c1",
          "on-surface": "#4f271a",
          "on-tertiary-container": "#396100",
          "on-secondary": "#f4faff",
          "on-tertiary": "#eeffd5",
          "surface-container-low": "#fff1ed",
          "tertiary-fixed": "#c1fd7c",
          "inverse-primary": "#fe893c",
          "on-surface-variant": "#845343",
          "on-primary-fixed-variant": "#733200",
          "tertiary-dim": "#375d00",
          "secondary-fixed": "#c2e8ff",
          "inverse-on-surface": "#ba9489",
          "on-primary": "#fff7f5",
          "tertiary": "#3f6a00",
          "secondary-container": "#c2e8ff",
          "on-primary-fixed": "#451c00",
          "secondary-dim": "#005a78",
          "surface-tint": "#9b4600",
          "primary": "#9b4600",
          "primary-fixed-dim": "#ff9a5c",
          "on-error-container": "#671200",
          "surface-container-lowest": "#ffffff",
          "primary-container": "#ffae80"
      },
      "borderRadius": {
          "DEFAULT": "1rem",
          "lg": "2rem",
          "xl": "3rem",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Plus Jakarta Sans"],
          "body": ["Be Vietnam Pro"],
          "label": ["Plus Jakarta Sans"]
      }
    },
  },
  plugins: [],
}
